# Generated by Django 5.0.6 on 2024-06-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_lc5',
        ),
    ]
