# Generated by Django 5.0.6 on 2024-06-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc5_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitrequest',
            name='lc1_letter',
            field=models.ImageField(blank=True, null=True, upload_to='lc1_letters'),
        ),
    ]
