# Generated by Django 5.0.6 on 2024-06-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc5_app', '0004_alter_permitrequest_lc1_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitrequest',
            name='lc1_letter',
            field=models.ImageField(null=True, upload_to='lc1_letters'),
        ),
    ]
