# Generated by Django 5.0.6 on 2024-06-10 16:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trader_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('purpose', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('a', 'Valid'), ('b', 'Expired')], max_length=1)),
                ('date_of_expiry', models.DateField(default=datetime.datetime(2024, 6, 11, 19, 53, 12, 794699))),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader_app.license')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_of_expiry', models.DateField(default=datetime.datetime(2024, 6, 11, 19, 53, 12, 794699))),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvo_app.animal')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader_app.license')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvo_app.permit')),
            ],
        ),
    ]
