# Generated by Django 5.0.6 on 2024-06-16 05:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('purpose', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('a', 'Valid'), ('b', 'Expired')], max_length=1)),
                ('date_of_expiry', models.DateField(default=datetime.datetime(2024, 6, 17, 8, 20, 46, 533052))),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_app.trader')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(default='M', max_length=1)),
                ('color', models.CharField(default='black', max_length=30)),
                ('quantity', models.IntegerField()),
                ('date_of_expiry', models.DateField(default=datetime.datetime(2024, 6, 17, 8, 20, 46, 533052))),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvo_app.animal')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_app.trader')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvo_app.permit')),
            ],
        ),
    ]
