# Generated by Django 5.0.6 on 2024-07-08 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animalinfo',
            name='date_of_expiry',
            field=models.DateField(default=datetime.datetime(2024, 7, 9, 10, 1, 1, 259833)),
        ),
        migrations.AlterField(
            model_name='permit',
            name='date_of_expiry',
            field=models.DateField(default=datetime.datetime(2024, 7, 9, 10, 1, 1, 258765)),
        ),
        migrations.AlterField(
            model_name='permit',
            name='status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('EXPIRED', 'Expired'), ('IN_TRANSIT', 'In Transit')], default='Valid', max_length=15),
        ),
    ]
