# Generated by Django 5.0.6 on 2024-07-08 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvo_app', '0002_permit_end_time_permit_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalinfo',
            name='date_of_expiry',
            field=models.DateField(default=datetime.datetime(2024, 7, 9, 17, 4, 12, 488140)),
        ),
        migrations.AlterField(
            model_name='permit',
            name='date_of_expiry',
            field=models.DateField(default=datetime.datetime(2024, 7, 9, 17, 4, 12, 485401)),
        ),
    ]
