# Generated by Django 5.0.6 on 2024-06-10 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvo_app', '0004_alter_animalinfo_date_of_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalinfo',
            name='date_of_expiry',
            field=models.DateField(default=datetime.datetime(2024, 6, 11, 21, 10, 50, 237296)),
        ),
        migrations.AlterField(
            model_name='permit',
            name='date_of_expiry',
            field=models.DateField(default=datetime.datetime(2024, 6, 11, 21, 10, 50, 237296)),
        ),
    ]
