# Generated by Django 5.0.6 on 2024-06-10 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='date_of_expiry',
            field=models.DateField(default=datetime.datetime(2025, 6, 10, 20, 27, 45, 743213)),
        ),
    ]
