# Generated by Django 5.0.6 on 2024-06-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitrequest',
            name='trader',
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='license_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
