# Generated by Django 5.0.6 on 2024-06-10 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader_app', '0002_alter_license_date_of_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='date_of_expiry',
            field=models.DateField(default=datetime.datetime(2025, 6, 10, 20, 52, 45, 622680)),
        ),
    ]
