# Generated by Django 5.0.6 on 2024-07-07 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('nin', models.CharField(max_length=30, unique=True)),
                ('license_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
                ('date_of_birth', models.DateField()),
                ('telephone', models.IntegerField(unique=True)),
                ('village', models.CharField(max_length=30)),
                ('parish', models.CharField(max_length=30)),
                ('s_county', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('date_approved', models.DateField(null=True)),
                ('date_rejected', models.DateField(null=True)),
                ('status', models.CharField(choices=[('a', 'Approved'), ('b', 'Rejected'), ('c', 'Submitted')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Quarantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=30)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_app.district')),
            ],
        ),
        migrations.CreateModel(
            name='TraderLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_app.trader')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
