# Generated by Django 5.0.6 on 2024-06-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=30)),
                ('animal', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('nin', models.CharField(max_length=30, unique=True)),
                ('license_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
                ('date_of_birth', models.DateField()),
                ('telephone', models.IntegerField(unique=True)),
                ('village', models.CharField(max_length=30)),
                ('parish', models.CharField(max_length=30)),
                ('s_county', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('date_approved', models.DateField(null=True)),
                ('date_rejected', models.DateField(null=True)),
                ('status', models.CharField(choices=[('a', 'Approved'), ('b', 'Rejected'), ('c', 'Submitted')], max_length=1)),
            ],
        ),
    ]
