# Generated by Django 5.0.6 on 2024-07-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
